# px_profile.ps1 - Layer 2 of the structure model: deterministic numeric profiles
# per part, measured from the FINALIZED dot database (commit cff3a07).
# No estimation anywhere: every number is computed from _pxmaster_hero.txt chars
# and the adjudicated _dots_*.txt memberships.
# Output: _pxprofile_hero.txt
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$W=352; $H=192

# ---------- load master map ----------
$mm = Get-Content (Join-Path $root "_pxmaster_hero.txt")
$gi=0; for ($i=0;$i -lt $mm.Count;$i++){ if ($mm[$i] -eq 'GRID:'){ $gi=$i+1; break } }
$palette = New-Object 'System.Collections.Generic.Dictionary[string,string]'
foreach ($l in $mm) {
  if ($l -match "^(.) = rgb\((\d+,\d+,\d+)\)") { $palette[$Matches[1]] = $Matches[2] }
  if ($l -eq 'GRID:') { break }
}

# ---------- tone tiers (for shading structure metrics) ----------
$tierOf = New-Object 'System.Collections.Generic.Dictionary[string,string]'
foreach ($c in @('K','1','2'))           { $tierOf[$c]='outline' }
foreach ($c in @('/','-','X','G','B'))   { $tierOf[$c]='deep' }
foreach ($c in @('d','r'))               { $tierOf[$c]='dark' }
foreach ($c in @('D'))                   { $tierOf[$c]='mid' }
foreach ($c in @('R','6','e'))           { $tierOf[$c]='core' }
foreach ($c in @('E','4'))               { $tierOf[$c]='bright' }
foreach ($c in @('S','8'))               { $tierOf[$c]='skin' }
foreach ($c in @('A','s','0'))           { $tierOf[$c]='skin-shade' }
foreach ($c in @('W','w','3'))           { $tierOf[$c]='white' }
foreach ($c in @('U','u'))               { $tierOf[$c]='lavender' }
foreach ($c in @('Y'))                   { $tierOf[$c]='yellow' }
foreach ($c in @('g'))                   { $tierOf[$c]='gray' }

# ---------- load all dots files ----------
$parts = New-Object 'System.Collections.Generic.Dictionary[string,object]'
$ownerMap = New-Object 'object[]' ($W*$H)   # each cell: ArrayList of part names
foreach ($f in (Get-ChildItem (Join-Path $root "_dots_*.txt") | Sort-Object Name)) {
  $part = $f.BaseName -replace '^_dots_',''
  $own = New-Object 'System.Collections.Generic.HashSet[int]'
  $sha = New-Object 'System.Collections.Generic.Dictionary[int,string]'   # dot -> partners string
  $sec = ""
  foreach ($l in (Get-Content $f.FullName -Encoding UTF8)) {
    $t=$l.Trim()
    if ($t -eq 'DOTS:') { $sec='D'; continue }
    if ($t -eq 'SHARED:' -or $t -eq 'AMBIGUOUS:') { $sec='S'; continue }
    if ($t -eq '' -or $t.StartsWith('#')) { continue }
    if ($t -match "^y=(\d+):\s*([^@]*)(@shared-with:(\S+))?") {
      $y=[int]$Matches[1]; $spec=$Matches[2]; $pn=$Matches[4]
      foreach ($tok in ($spec.Trim() -split '\s+')) {
        $a=-1;$b=-1
        if ($tok -match "^(\d+)-(\d+)$") { $a=[int]$Matches[1]; $b=[int]$Matches[2] }
        elseif ($tok -match "^(\d+)$") { $a=[int]$Matches[1]; $b=$a }
        if ($a -lt 0) { continue }
        for ($x=$a;$x -le $b;$x++) {
          $i=$y*$W+$x
          if ($sec -eq 'D') { [void]$own.Add($i) } else { $sha[$i] = $pn }
          if ($null -eq $ownerMap[$i]) { $ownerMap[$i] = New-Object System.Collections.ArrayList }
          if (-not $ownerMap[$i].Contains($part)) { [void]$ownerMap[$i].Add($part) }
        }
      }
    }
  }
  $parts[$part] = @{ own=$own; shared=$sha }
}

# ---------- per-part metrics ----------
$out = New-Object System.Collections.ArrayList
[void]$out.Add("# _pxprofile_hero.txt - Layer 2 numeric profiles (deterministic measurement)")
[void]$out.Add("# source: _pxmaster_hero.txt + finalized _dots_*.txt (commit cff3a07)")
[void]$out.Add("# generated by tools/px_profile.ps1")
[void]$out.Add("")

foreach ($pname in ($parts.Keys | Sort-Object)) {
  $own = $parts[$pname].own
  $sha = $parts[$pname].shared
  $all = New-Object 'System.Collections.Generic.HashSet[int]'
  foreach ($i in $own) { [void]$all.Add($i) }
  foreach ($i in $sha.Keys) { [void]$all.Add($i) }

  # bbox / rows / colors / tiers / centroids
  $minX=9999;$maxX=-1;$minY=9999;$maxY=-1
  $colCount = New-Object 'System.Collections.Generic.Dictionary[string,int]'
  $tierCount = New-Object 'System.Collections.Generic.Dictionary[string,int]'
  $rows = New-Object 'System.Collections.Generic.Dictionary[int,object]'
  $sumX=0.0;$sumY=0.0
  $brightX=0.0;$brightY=0.0;$nBright=0
  $darkX=0.0;$darkY=0.0;$nDark=0
  foreach ($i in $all) {
    $y=[math]::Floor($i/$W); $x=$i%$W
    if($x -lt $minX){$minX=$x}; if($x -gt $maxX){$maxX=$x}
    if($y -lt $minY){$minY=$y}; if($y -gt $maxY){$maxY=$y}
    $sumX+=$x; $sumY+=$y
    $ch=[string]$mm[$gi+$y][$x]
    if ($colCount.ContainsKey($ch)) { $colCount[$ch]++ } else { $colCount[$ch]=1 }
    $tier = "other"; if ($tierOf.ContainsKey($ch)) { $tier=$tierOf[$ch] }
    if ($tierCount.ContainsKey($tier)) { $tierCount[$tier]++ } else { $tierCount[$tier]=1 }
    if ($tier -eq 'bright' -or $tier -eq 'skin' -or $tier -eq 'white') { $brightX+=$x;$brightY+=$y;$nBright++ }
    if ($tier -eq 'dark' -or $tier -eq 'deep' -or $tier -eq 'skin-shade') { $darkX+=$x;$darkY+=$y;$nDark++ }
    if (-not $rows.ContainsKey($y)) { $rows[$y] = @{min=$x;max=$x;n=1} }
    else {
      if ($x -lt $rows[$y].min) { $rows[$y].min=$x }
      if ($x -gt $rows[$y].max) { $rows[$y].max=$x }
      $rows[$y].n++
    }
  }
  $n = $all.Count
  if ($n -eq 0) { continue }

  # adjacency: for each dot, check 4-neighbors owned by other parts / transparent
  $adj = New-Object 'System.Collections.Generic.Dictionary[string,int]'
  foreach ($i in $all) {
    $y=[math]::Floor($i/$W); $x=$i%$W
    $touched = New-Object 'System.Collections.Generic.HashSet[string]'
    foreach ($d in @(@(-1,0),@(1,0),@(0,-1),@(0,1))) {
      $nx=$x+$d[0]; $ny=$y+$d[1]
      if ($nx -lt 0 -or $nx -ge $W -or $ny -lt 0 -or $ny -ge $H) { [void]$touched.Add("(canvas-edge)"); continue }
      $j=$ny*$W+$nx
      $ol = $ownerMap[$j]
      if ($null -eq $ol) { [void]$touched.Add("(transparent)"); continue }
      foreach ($q in $ol) { if ($q -ne $pname) { [void]$touched.Add($q) } }
    }
    foreach ($q in $touched) {
      if ($adj.ContainsKey($q)) { $adj[$q]++ } else { $adj[$q]=1 }
    }
  }

  # shared partners summary
  $shaCnt = New-Object 'System.Collections.Generic.Dictionary[string,int]'
  foreach ($kv in $sha.GetEnumerator()) {
    $pn = $kv.Value; if ($null -eq $pn) { $pn = "(unspecified)" }
    if ($shaCnt.ContainsKey($pn)) { $shaCnt[$pn]++ } else { $shaCnt[$pn]=1 }
  }

  [void]$out.Add("PART: $pname")
  [void]$out.Add(("  dots: {0} own + {1} shared = {2}" -f $own.Count,$sha.Count,$n))
  [void]$out.Add(("  bbox: ({0},{1})-({2},{3})  w={4} h={5}" -f $minX,$minY,$maxX,$maxY,($maxX-$minX+1),($maxY-$minY+1)))
  [void]$out.Add(("  centroid: ({0:F1},{1:F1})" -f ($sumX/$n),($sumY/$n)))
  $cs = ($colCount.GetEnumerator() | Sort-Object Value -Descending | ForEach-Object { "$($_.Key)($($palette[$_.Key]))x$($_.Value)" }) -join " "
  [void]$out.Add("  colors: $cs")
  $ts = ($tierCount.GetEnumerator() | Sort-Object Value -Descending | ForEach-Object { "{0}={1}({2:F0}%)" -f $_.Key,$_.Value,(100.0*$_.Value/$n) }) -join " "
  [void]$out.Add("  tiers: $ts")
  if ($nBright -gt 0 -and $nDark -gt 0) {
    $dx = ($darkX/$nDark)-($brightX/$nBright); $dy = ($darkY/$nDark)-($brightY/$nBright)
    [void]$out.Add(("  shading: bright_centroid=({0:F1},{1:F1}) dark_centroid=({2:F1},{3:F1}) shadow_offset=({4:F1},{5:F1})" -f ($brightX/$nBright),($brightY/$nBright),($darkX/$nDark),($darkY/$nDark),$dx,$dy))
  }
  $as = ($adj.GetEnumerator() | Sort-Object Value -Descending | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join " "
  [void]$out.Add("  adjacency(border dots): $as")
  if ($shaCnt.Count -gt 0) {
    $ss = ($shaCnt.GetEnumerator() | Sort-Object Value -Descending | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join " "
    [void]$out.Add("  shared-outline partners: $ss")
  }
  [void]$out.Add("  width-profile (y: xmin-xmax n):")
  foreach ($y in ($rows.Keys | Sort-Object)) {
    [void]$out.Add(("    y={0}: {1}-{2} n={3} w={4}" -f $y,$rows[$y].min,$rows[$y].max,$rows[$y].n,($rows[$y].max-$rows[$y].min+1)))
  }
  [void]$out.Add("")
}
$out -join "`n" | Out-File (Join-Path $root "_pxprofile_hero.txt") -Encoding ascii
Write-Host "wrote _pxprofile_hero.txt ($($parts.Count) parts)"
